# Generated by Django 5.2 on 2025-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
